/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VistasContratos;

/**
 *
 * @author Aaron Diaz
 */
public class FrmBuscarContrato extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscarContrato.class.getName());

    /**
     * Creates new form FrmBuscarContrato
     */
    public FrmBuscarContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltros = new javax.swing.JPanel();
        lblFiltroNumero = new javax.swing.JLabel();
        txtFiltroNumero = new javax.swing.JTextField();
        lblFiltroCliente = new javax.swing.JLabel();
        txtFiltroCliente = new javax.swing.JTextField();
        lblFiltroEspacio = new javax.swing.JLabel();
        cmbFiltroEspacio = new javax.swing.JComboBox<>();
        lblFiltroFecha = new javax.swing.JLabel();
        dateFiltroFecha = new com.toedter.calendar.JDateChooser();
        lblFiltroEstado = new javax.swing.JLabel();
        cmbFiltroEstado = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        pnlResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();
        pnlBotonesBusqueda = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelarBusqueda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Contratos");
        setModal(true);

        pnlFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Contratos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        lblFiltroNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFiltroNumero.setText("N° contrato:");
        lblFiltroNumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtFiltroNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblFiltroCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFiltroCliente.setText("   Cliente:");

        txtFiltroCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblFiltroEspacio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFiltroEspacio.setText("  Espacio:");

        cmbFiltroEspacio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbFiltroEspacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pequeño", "Mediano", "Grande" }));

        lblFiltroFecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFiltroFecha.setText("  Fecha: ");

        dateFiltroFecha.setDateFormatString("dd/MM/yyyy");
        dateFiltroFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblFiltroEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFiltroEstado.setText("  Estado:");

        cmbFiltroEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbFiltroEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pendiente", "Activo", "Finalizado", "Cancelado" }));

        btnFiltrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");

        javax.swing.GroupLayout pnlFiltrosLayout = new javax.swing.GroupLayout(pnlFiltros);
        pnlFiltros.setLayout(pnlFiltrosLayout);
        pnlFiltrosLayout.setHorizontalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblFiltroNumero)
                .addGap(5, 5, 5)
                .addComponent(txtFiltroNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFiltroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFiltroEspacio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFiltroEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFiltroFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFiltroEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar)
                .addContainerGap())
        );
        pnlFiltrosLayout.setVerticalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblFiltroNumero))
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtFiltroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFiltroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFiltroCliente)
                            .addComponent(lblFiltroEspacio)
                            .addComponent(cmbFiltroEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFiltroFecha)))
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateFiltroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFiltrar)
                                .addComponent(lblFiltroEstado)))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tblContratos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Identificación", "Cliente", "Espacio", "Fecha de inicio", "Finaliza", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContratos);

        javax.swing.GroupLayout pnlResultadoLayout = new javax.swing.GroupLayout(pnlResultado);
        pnlResultado.setLayout(pnlResultadoLayout);
        pnlResultadoLayout.setHorizontalGroup(
            pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlResultadoLayout.setVerticalGroup(
            pnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlBotonesBusqueda.setLayout(new java.awt.GridLayout(1, 2));

        btnAceptar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        pnlBotonesBusqueda.add(btnAceptar);

        btnCancelarBusqueda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarBusqueda.setText("Cancelar búsqueda");
        btnCancelarBusqueda.addActionListener(this::btnCancelarBusquedaActionPerformed);
        pnlBotonesBusqueda.add(btnCancelarBusqueda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(798, 798, 798)
                .addComponent(pnlBotonesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotonesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusquedaActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmBuscarContrato dialog = new FrmBuscarContrato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelarBusqueda;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cmbFiltroEspacio;
    private javax.swing.JComboBox<String> cmbFiltroEstado;
    private com.toedter.calendar.JDateChooser dateFiltroFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltroCliente;
    private javax.swing.JLabel lblFiltroEspacio;
    private javax.swing.JLabel lblFiltroEstado;
    private javax.swing.JLabel lblFiltroFecha;
    private javax.swing.JLabel lblFiltroNumero;
    private javax.swing.JPanel pnlBotonesBusqueda;
    private javax.swing.JPanel pnlFiltros;
    private javax.swing.JPanel pnlResultado;
    private javax.swing.JTable tblContratos;
    private javax.swing.JTextField txtFiltroCliente;
    private javax.swing.JTextField txtFiltroNumero;
    // End of variables declaration//GEN-END:variables
}
