/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFramesStorageBox;
import JFramesStorageBox.FrmBuscarContrato;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import modelos.Servicio;
import lists.ServiciosList;
/**
 *
 * @author Aaron Diaz
 */
public class FrmContrato extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmContrato.class.getName());
    private DefaultTableModel modeloTabla;
    private ServiciosList catalogoServicios;
    private ArrayList<Servicio> servicioSeleccionados;
    /**
     * Creates new form FrmContratos
     */
    public FrmContrato() {
        initComponents();
        setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel) tblServiciosContrato.getModel();
        modeloTabla.setRowCount(0);
        
        servicioSeleccionados = new ArrayList<>();
        catalogoServicios = new ServiciosList();
        cargarComboServicios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNumeroContrato = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        pnlCliente = new javax.swing.JPanel();
        txtIdentificacionCliente = new javax.swing.JTextField();
        btnValidarCliente = new javax.swing.JButton();
        lblNombreCliente = new javax.swing.JLabel();
        lblidentificacion = new javax.swing.JLabel();
        pnlEspacio = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        cmbTipoEspacio = new javax.swing.JComboBox<>();
        btnBuscarDisponible = new javax.swing.JButton();
        lblEspacioAsignado = new javax.swing.JLabel();
        pnlFechas = new javax.swing.JPanel();
        dateFechaInicio = new com.toedter.calendar.JDateChooser();
        dateFechaFinal = new com.toedter.calendar.JDateChooser();
        lblDiasPeriodos = new javax.swing.JLabel();
        lbltext = new javax.swing.JLabel();
        lbltext1 = new javax.swing.JLabel();
        pnlServicios = new javax.swing.JPanel();
        cmbServicios = new javax.swing.JComboBox<>();
        btnAgregarServicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServiciosContrato = new javax.swing.JTable();
        pnlCostos = new javax.swing.JPanel();
        jplSubtotal = new javax.swing.JPanel();
        lblTituloSubTotal = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jplImpuesto = new javax.swing.JPanel();
        lblTituloImpuesto = new javax.swing.JLabel();
        lblImpuesto = new javax.swing.JLabel();
        pnlTotal = new javax.swing.JPanel();
        lblTituloTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnCancelarContrato = new javax.swing.JButton();
        btnBuscarContrato = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Contratos");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("N° contrato:");

        lblNumeroContrato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Estado:");

        lblEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(7, 7, 7))))
        );

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N
        pnlCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        txtIdentificacionCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdentificacionCliente.setToolTipText("Ingrese la identificacion sin guiones");
        txtIdentificacionCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionClienteKeyTyped(evt);
            }
        });

        btnValidarCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnValidarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/garrapata (1).png"))); // NOI18N
        btnValidarCliente.setText("Validar");

        lblNombreCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblidentificacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblidentificacion.setText("Identificación");

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblidentificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValidarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(lblNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnValidarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdentificacionCliente)
                        .addComponent(lblidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pnlEspacio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N
        pnlEspacio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        lbl1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl1.setText("Tipo:");

        cmbTipoEspacio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbTipoEspacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        cmbTipoEspacio.setToolTipText("Selecciones el tipo de espacio a alquilar");

        btnBuscarDisponible.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarDisponible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscarDisponible.setText("Buscar espacio");
        btnBuscarDisponible.setToolTipText("Buscara espacios disponibles");
        btnBuscarDisponible.addActionListener(this::btnBuscarDisponibleActionPerformed);

        lblEspacioAsignado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEspacioAsignado.setText("Espacio asignado: ");

        javax.swing.GroupLayout pnlEspacioLayout = new javax.swing.GroupLayout(pnlEspacio);
        pnlEspacio.setLayout(pnlEspacioLayout);
        pnlEspacioLayout.setHorizontalGroup(
            pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspacioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEspacioLayout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarDisponible)
                    .addComponent(lblEspacioAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pnlEspacioLayout.setVerticalGroup(
            pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEspacioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblEspacioAsignado)
                .addContainerGap())
        );

        pnlFechas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fechas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N
        pnlFechas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        dateFechaInicio.setDateFormatString("dd/MM/yyyy");
        dateFechaInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        dateFechaFinal.setToolTipText("\n");
        dateFechaFinal.setDateFormatString("dd/MM/yyyy");
        dateFechaFinal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblDiasPeriodos.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblDiasPeriodos.setText("Días: - / Periodos: -");

        lbltext.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbltext.setText("Inicio");

        lbltext1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbltext1.setText("Fin");

        javax.swing.GroupLayout pnlFechasLayout = new javax.swing.GroupLayout(pnlFechas);
        pnlFechas.setLayout(pnlFechasLayout);
        pnlFechasLayout.setHorizontalGroup(
            pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDiasPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFechasLayout.createSequentialGroup()
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFechasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFechasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(dateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(pnlFechasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lbltext1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlFechasLayout.setVerticalGroup(
            pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltext1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDiasPeriodos)
                .addContainerGap())
        );

        pnlServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servicios adicionales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        cmbServicios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarServicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/signo-positivo.png"))); // NOI18N
        btnAgregarServicio.setText(" Agregar");

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblServiciosContrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblServiciosContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Servicio", "Precio", "Quitar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblServiciosContrato);

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(cmbServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbServicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCostos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen de costo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15))); // NOI18N

        jplSubtotal.setBackground(new java.awt.Color(240, 240, 240));
        jplSubtotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));

        lblTituloSubTotal.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTituloSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSubTotal.setText("Subtotal");

        lblSubTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jplSubtotalLayout = new javax.swing.GroupLayout(jplSubtotal);
        jplSubtotal.setLayout(jplSubtotalLayout);
        jplSubtotalLayout.setHorizontalGroup(
            jplSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplSubtotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jplSubtotalLayout.setVerticalGroup(
            jplSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplSubtotalLayout.createSequentialGroup()
                .addComponent(lblTituloSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jplImpuesto.setBackground(new java.awt.Color(240, 240, 240));
        jplImpuesto.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));

        lblTituloImpuesto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTituloImpuesto.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloImpuesto.setText("Impuesto");

        lblImpuesto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblImpuesto.setForeground(new java.awt.Color(0, 0, 0));
        lblImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jplImpuestoLayout = new javax.swing.GroupLayout(jplImpuesto);
        jplImpuesto.setLayout(jplImpuestoLayout);
        jplImpuestoLayout.setHorizontalGroup(
            jplImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplImpuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(lblImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jplImpuestoLayout.setVerticalGroup(
            jplImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplImpuestoLayout.createSequentialGroup()
                .addComponent(lblTituloImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTotal.setBackground(new java.awt.Color(21, 94, 165));
        pnlTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));

        lblTituloTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTituloTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTotal.setText("Total");

        lblTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addComponent(lblTituloTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlCostosLayout = new javax.swing.GroupLayout(pnlCostos);
        pnlCostos.setLayout(pnlCostosLayout);
        pnlCostosLayout.setHorizontalGroup(
            pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCostosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jplSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCostosLayout.setVerticalGroup(
            pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCostosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jplImpuesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jplSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/crear.png"))); // NOI18N
        btnCrear.setText("Crear");

        btnActivar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-de-play.png"))); // NOI18N
        btnActivar.setText("Activar");
        btnActivar.setEnabled(false);

        btnFinalizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bandera.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setEnabled(false);

        btnCancelarContrato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/senal-de-stop.png"))); // NOI18N
        btnCancelarContrato.setText("Cancelar");
        btnCancelarContrato.setEnabled(false);

        btnBuscarContrato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscarContrato.setText("Buscar contratos");
        btnBuscarContrato.addActionListener(this::btnBuscarContratoActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refresco.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActivar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnActivar)
                    .addComponent(btnFinalizar)
                    .addComponent(btnCancelarContrato)
                    .addComponent(btnBuscarContrato)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(pnlServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarContratoActionPerformed
        FrmBuscarContrato buscar = new FrmBuscarContrato(this, true);
        buscar.setVisible(true);
    }//GEN-LAST:event_btnBuscarContratoActionPerformed

    private void txtIdentificacionClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionClienteKeyTyped
        char tecla = evt.getKeyChar();
        boolean esNumero = (tecla >= '0' && tecla <= '9');

        if (esNumero == false) {
            evt.consume();
        }
        if(txtIdentificacionCliente.getText().length() >= 10){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacionClienteKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdentificacionCliente.setText("");
        lblNombreCliente.setText("");
        cmbTipoEspacio.setSelectedIndex(0);
        lblEspacioAsignado.setText("Espacio asignado: ");
        dateFechaInicio.setDate(null);
        dateFechaFinal.setDate(null);
        lblDiasPeriodos.setText("Días: - / Periodos: -");
        lblSubTotal.setText("₡0");
        lblImpuesto.setText("₡0");
        lblTotal.setText("₡0");
        lblEstado.setText("Sin contrato");
        lblNumeroContrato.setText("-");
        //todo; limpiar tblServiciosContratos cuando este conectado el modelo defaulttablemodel
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDisponibleActionPerformed
    private void cargarComboServicios(){
        cmbServicios.removeAllItems();
        for (Servicio servi : catalogoServicios.getList()) {
            cmbServicios.addItem(servi);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmContrato().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnBuscarContrato;
    private javax.swing.JButton btnBuscarDisponible;
    private javax.swing.JButton btnCancelarContrato;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnValidarCliente;
    private javax.swing.JComboBox<Object> cmbServicios;
    private javax.swing.JComboBox<String> cmbTipoEspacio;
    private com.toedter.calendar.JDateChooser dateFechaFinal;
    private com.toedter.calendar.JDateChooser dateFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jplImpuesto;
    private javax.swing.JPanel jplSubtotal;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblDiasPeriodos;
    private javax.swing.JLabel lblEspacioAsignado;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumeroContrato;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTituloImpuesto;
    private javax.swing.JLabel lblTituloSubTotal;
    private javax.swing.JLabel lblTituloTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblidentificacion;
    private javax.swing.JLabel lbltext;
    private javax.swing.JLabel lbltext1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlCostos;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlEspacio;
    private javax.swing.JPanel pnlFechas;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JTable tblServiciosContrato;
    private javax.swing.JTextField txtIdentificacionCliente;
    // End of variables declaration//GEN-END:variables
}
