/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2;

import JFramesStorageBox.FrmCliente;
import JFramesStorageBox.FrmServicios;
import JFramesStorageBox.FrmContrato;
import JFramesStorageBox.FrmEspacio;
import java.util.ArrayList;
import modelos.Cliente;

/**
 *
 * @author Aaron Diaz
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    

private lists.EmpleadoList listaEmpleados = new lists.EmpleadoList();

private Controladores.controladorEmpleado controladorEmp =
        new Controladores.controladorEmpleado(listaEmpleados);

private FrmCliente frmcliente;
private Controladores.ControladorCliente ctrCliente;

    /**
     * Creates new form FrmMenuPrincipal
     */
public FrmMenuPrincipal() {
    initComponents();
    setLocationRelativeTo(null);

    ctrCliente = Controladores.ControladorCliente.getInstancia();

    frmcliente = new FrmCliente();
}

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

   
    /**
     * Creates new form FrmMenuPrincipal
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();
        pnlClientes = new javax.swing.JPanel();
        pnlFranjaClientes = new javax.swing.JPanel();
        lblFlechaClientes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        pnlEspacios = new javax.swing.JPanel();
        pnlFranjaEspacios = new javax.swing.JPanel();
        lblFlechaEspacios = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        pnlContratos = new javax.swing.JPanel();
        pnlFranjaContratos = new javax.swing.JPanel();
        lblFlechaContratos = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        pnlServicios = new javax.swing.JPanel();
        pnlFranjaServicios = new javax.swing.JPanel();
        lblFlechaServicios = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        pnlEmpleados = new javax.swing.JPanel();
        pnlFranjaEmpleados = new javax.swing.JPanel();
        lblFlechaEmpleados = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StorageBox-Menú Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(237, 239, 242)));
        jPanel1.setPreferredSize(new java.awt.Dimension(454, 100));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 44, 83));
        jLabel1.setText("StorageBox");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 143, 152));
        jLabel2.setText("Selecciona un módula para continuar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnlCentral.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentral.setLayout(new javax.swing.BoxLayout(pnlCentral, javax.swing.BoxLayout.Y_AXIS));

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlClientes.setPreferredSize(new java.awt.Dimension(582, 55));
        pnlClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClientesMouseClicked(evt);
            }
        });
        pnlClientes.setLayout(new java.awt.BorderLayout());

        pnlFranjaClientes.setBackground(new java.awt.Color(46, 134, 171));
        pnlFranjaClientes.setPreferredSize(new java.awt.Dimension(9, 32));

        javax.swing.GroupLayout pnlFranjaClientesLayout = new javax.swing.GroupLayout(pnlFranjaClientes);
        pnlFranjaClientes.setLayout(pnlFranjaClientesLayout);
        pnlFranjaClientesLayout.setHorizontalGroup(
            pnlFranjaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlFranjaClientesLayout.setVerticalGroup(
            pnlFranjaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        pnlClientes.add(pnlFranjaClientes, java.awt.BorderLayout.LINE_START);

        lblFlechaClientes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFlechaClientes.setForeground(new java.awt.Color(199, 205, 212));
        lblFlechaClientes.setText(">");
        pnlClientes.add(lblFlechaClientes, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 44, 83));
        jLabel3.setText(" Clientes");
        jPanel3.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(138, 143, 152));
        jLabel4.setText(" Gestión de clientes registrados");
        jPanel3.add(jLabel4);

        pnlClientes.add(jPanel3, java.awt.BorderLayout.CENTER);

        pnlCentral.add(pnlClientes);

        jPanel12.setBackground(new java.awt.Color(241, 243, 245));
        jPanel12.setPreferredSize(new java.awt.Dimension(574, 1));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlCentral.add(jPanel12);

        pnlEspacios.setBackground(new java.awt.Color(255, 255, 255));
        pnlEspacios.setPreferredSize(new java.awt.Dimension(582, 55));
        pnlEspacios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEspaciosMouseClicked(evt);
            }
        });
        pnlEspacios.setLayout(new java.awt.BorderLayout());

        pnlFranjaEspacios.setBackground(new java.awt.Color(46, 134, 171));
        pnlFranjaEspacios.setPreferredSize(new java.awt.Dimension(9, 32));

        javax.swing.GroupLayout pnlFranjaEspaciosLayout = new javax.swing.GroupLayout(pnlFranjaEspacios);
        pnlFranjaEspacios.setLayout(pnlFranjaEspaciosLayout);
        pnlFranjaEspaciosLayout.setHorizontalGroup(
            pnlFranjaEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlFranjaEspaciosLayout.setVerticalGroup(
            pnlFranjaEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        pnlEspacios.add(pnlFranjaEspacios, java.awt.BorderLayout.LINE_START);

        lblFlechaEspacios.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFlechaEspacios.setForeground(new java.awt.Color(199, 205, 212));
        lblFlechaEspacios.setText(">");
        pnlEspacios.add(lblFlechaEspacios, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(4, 44, 83));
        jLabel10.setText(" Espacios");
        jPanel8.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(138, 143, 152));
        jLabel11.setText(" Disponibilidad y asignación");
        jPanel8.add(jLabel11);

        pnlEspacios.add(jPanel8, java.awt.BorderLayout.CENTER);

        pnlCentral.add(pnlEspacios);

        jPanel13.setBackground(new java.awt.Color(241, 243, 245));
        jPanel13.setPreferredSize(new java.awt.Dimension(574, 1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlCentral.add(jPanel13);

        pnlContratos.setBackground(new java.awt.Color(244, 249, 253));
        pnlContratos.setPreferredSize(new java.awt.Dimension(582, 55));
        pnlContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlContratosMouseClicked(evt);
            }
        });
        pnlContratos.setLayout(new java.awt.BorderLayout());

        pnlFranjaContratos.setBackground(new java.awt.Color(46, 134, 171));
        pnlFranjaContratos.setPreferredSize(new java.awt.Dimension(9, 32));

        javax.swing.GroupLayout pnlFranjaContratosLayout = new javax.swing.GroupLayout(pnlFranjaContratos);
        pnlFranjaContratos.setLayout(pnlFranjaContratosLayout);
        pnlFranjaContratosLayout.setHorizontalGroup(
            pnlFranjaContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlFranjaContratosLayout.setVerticalGroup(
            pnlFranjaContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        pnlContratos.add(pnlFranjaContratos, java.awt.BorderLayout.LINE_START);

        lblFlechaContratos.setBackground(new java.awt.Color(24, 95, 165));
        lblFlechaContratos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFlechaContratos.setForeground(new java.awt.Color(199, 205, 212));
        lblFlechaContratos.setText(">");
        pnlContratos.add(lblFlechaContratos, java.awt.BorderLayout.LINE_END);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(4, 44, 83));
        jLabel12.setText(" Contratos");
        jPanel9.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(138, 143, 152));
        jLabel13.setText(" Registro y consulta de contratos");
        jPanel9.add(jLabel13);

        pnlContratos.add(jPanel9, java.awt.BorderLayout.CENTER);

        pnlCentral.add(pnlContratos);

        jPanel15.setBackground(new java.awt.Color(241, 243, 245));
        jPanel15.setPreferredSize(new java.awt.Dimension(574, 1));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlCentral.add(jPanel15);

        pnlServicios.setBackground(new java.awt.Color(255, 255, 255));
        pnlServicios.setPreferredSize(new java.awt.Dimension(582, 55));
        pnlServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlServiciosMouseClicked(evt);
            }
        });
        pnlServicios.setLayout(new java.awt.BorderLayout());

        pnlFranjaServicios.setBackground(new java.awt.Color(46, 134, 171));
        pnlFranjaServicios.setPreferredSize(new java.awt.Dimension(9, 32));

        javax.swing.GroupLayout pnlFranjaServiciosLayout = new javax.swing.GroupLayout(pnlFranjaServicios);
        pnlFranjaServicios.setLayout(pnlFranjaServiciosLayout);
        pnlFranjaServiciosLayout.setHorizontalGroup(
            pnlFranjaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlFranjaServiciosLayout.setVerticalGroup(
            pnlFranjaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        pnlServicios.add(pnlFranjaServicios, java.awt.BorderLayout.LINE_START);

        lblFlechaServicios.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFlechaServicios.setForeground(new java.awt.Color(199, 205, 212));
        lblFlechaServicios.setText(">");
        pnlServicios.add(lblFlechaServicios, java.awt.BorderLayout.LINE_END);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(4, 44, 83));
        jLabel14.setText(" Servicios");
        jPanel10.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(138, 143, 152));
        jLabel15.setText(" Servicio adicionales por contrato");
        jPanel10.add(jLabel15);

        pnlServicios.add(jPanel10, java.awt.BorderLayout.CENTER);

        pnlCentral.add(pnlServicios);

        jPanel14.setBackground(new java.awt.Color(241, 243, 245));
        jPanel14.setPreferredSize(new java.awt.Dimension(574, 1));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlCentral.add(jPanel14);

        pnlEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmpleados.setPreferredSize(new java.awt.Dimension(582, 55));
        pnlEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEmpleadosMouseClicked(evt);
            }
        });
        pnlEmpleados.setLayout(new java.awt.BorderLayout());

        pnlFranjaEmpleados.setBackground(new java.awt.Color(46, 134, 171));
        pnlFranjaEmpleados.setPreferredSize(new java.awt.Dimension(9, 32));

        javax.swing.GroupLayout pnlFranjaEmpleadosLayout = new javax.swing.GroupLayout(pnlFranjaEmpleados);
        pnlFranjaEmpleados.setLayout(pnlFranjaEmpleadosLayout);
        pnlFranjaEmpleadosLayout.setHorizontalGroup(
            pnlFranjaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlFranjaEmpleadosLayout.setVerticalGroup(
            pnlFranjaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        pnlEmpleados.add(pnlFranjaEmpleados, java.awt.BorderLayout.LINE_START);

        lblFlechaEmpleados.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFlechaEmpleados.setForeground(new java.awt.Color(199, 205, 212));
        lblFlechaEmpleados.setText(">");
        pnlEmpleados.add(lblFlechaEmpleados, java.awt.BorderLayout.LINE_END);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(4, 44, 83));
        jLabel16.setText(" Empleados");
        jPanel11.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(138, 143, 152));
        jLabel17.setText(" Gestión personal del sistema");
        jPanel11.add(jLabel17);

        pnlEmpleados.add(jPanel11, java.awt.BorderLayout.CENTER);

        pnlCentral.add(pnlEmpleados);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(192, 80, 77));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 196, 195)));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCentral.add(jPanel16);

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseClicked
        resaltarFila(pnlClientes, pnlFranjaClientes,  lblFlechaClientes);
        new FrmCliente().setVisible(true);
        
    }//GEN-LAST:event_pnlClientesMouseClicked

    private void pnlEspaciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEspaciosMouseClicked
        resaltarFila(pnlEspacios, pnlFranjaEspacios,  lblFlechaEspacios);
        new FrmEspacio().setVisible(true);
    }//GEN-LAST:event_pnlEspaciosMouseClicked

    private void pnlContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlContratosMouseClicked
        resaltarFila(pnlContratos, pnlFranjaContratos,  lblFlechaContratos);
        new FrmContrato().setVisible(true);
    }//GEN-LAST:event_pnlContratosMouseClicked

    private void pnlServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlServiciosMouseClicked
        resaltarFila(pnlServicios, pnlFranjaServicios,  lblFlechaServicios);
        new FrmServicios().setVisible(true);
    }//GEN-LAST:event_pnlServiciosMouseClicked

    private void pnlEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEmpleadosMouseClicked
        resaltarFila(pnlEmpleados, pnlFranjaEmpleados, lblFlechaEmpleados);
        new JFramesStorageBox.FrmEmpleado(controladorEmp).setVisible(true);
    }//GEN-LAST:event_pnlEmpleadosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void resaltarFila(javax.swing.JPanel filaActiva, javax.swing.JPanel franjaActiva, javax.swing.JLabel flechaActiva){
        java.awt.Color blanco = java.awt.Color.WHITE;
        java.awt.Color celesteTenue = new java.awt.Color(244, 249, 253);
        java.awt.Color azulAcento = new java.awt.Color(46, 134, 171);
        java.awt.Color azulOscuro = new java.awt.Color(24, 95, 165);
        java.awt.Color gris = new java.awt.Color(199, 205, 212);
    
        pnlClientes.setBackground(blanco);
        pnlFranjaClientes.setBackground(azulAcento);
        lblFlechaClientes.setForeground(gris);
        
        pnlEspacios.setBackground(blanco);
        pnlFranjaEspacios.setBackground(azulAcento);
        lblFlechaEspacios.setForeground(gris);

        pnlContratos.setBackground(blanco);
        pnlFranjaContratos.setBackground(azulAcento);
        lblFlechaContratos.setForeground(gris);
        
        pnlServicios.setBackground(blanco);
        pnlFranjaServicios.setBackground(azulAcento);
        lblFlechaServicios.setForeground(gris);

        pnlEmpleados.setBackground(blanco);
        pnlFranjaEmpleados.setBackground(azulAcento);
        lblFlechaEmpleados.setForeground(gris);

        filaActiva.setBackground(celesteTenue);
        franjaActiva.setBackground(azulOscuro);
        flechaActiva.setForeground(azulOscuro);
    }   
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {

    try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }

    } catch (Exception ex) {
        System.out.println("No se pudo cargar Nimbus: " + ex.getMessage());
    }

    java.awt.EventQueue.invokeLater(() -> {
        new FrmMenuPrincipal().setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblFlechaClientes;
    private javax.swing.JLabel lblFlechaContratos;
    private javax.swing.JLabel lblFlechaEmpleados;
    private javax.swing.JLabel lblFlechaEspacios;
    private javax.swing.JLabel lblFlechaServicios;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlContratos;
    private javax.swing.JPanel pnlEmpleados;
    private javax.swing.JPanel pnlEspacios;
    private javax.swing.JPanel pnlFranjaClientes;
    private javax.swing.JPanel pnlFranjaContratos;
    private javax.swing.JPanel pnlFranjaEmpleados;
    private javax.swing.JPanel pnlFranjaEspacios;
    private javax.swing.JPanel pnlFranjaServicios;
    private javax.swing.JPanel pnlServicios;
    // End of variables declaration//GEN-END:variables
}
